# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '/opt/opt2/PycharmProjects/main_avito_django_bot/avito_parser_django/avito/PyQT5/View_task.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(755, 634)
        MainWindow.setMinimumSize(QtCore.QSize(740, 580))
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.tabWidget = QtWidgets.QTabWidget(self.centralwidget)
        self.tabWidget.setGeometry(QtCore.QRect(10, 10, 731, 581))
        self.tabWidget.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.tabWidget.setStyleSheet("text-align: left;\n"
"css\n"
"QLineEdit#urlLineEdit {\n"
"  padding: 2px;\n"
"  border: 1px solid #ccc;\n"
"  border-radius: 4px;\n"
"  background-color: #62a6ff;\n"
"  color: #000;\n"
"  text-align: left;\n"
"}\n"
"")
        self.tabWidget.setTabPosition(QtWidgets.QTabWidget.North)
        self.tabWidget.setObjectName("tabWidget")
        self.tab = QtWidgets.QWidget()
        self.tab.setObjectName("tab")
        self.Get_Task = QtWidgets.QPushButton(self.tab)
        self.Get_Task.setGeometry(QtCore.QRect(10, 450, 94, 26))
        self.Get_Task.setObjectName("Get_Task")
        self.View_Task = QtWidgets.QTableView(self.tab)
        self.View_Task.setGeometry(QtCore.QRect(15, 350, 701, 91))
        self.View_Task.setObjectName("View_Task")
        self.verticalLayoutWidget = QtWidgets.QWidget(self.tab)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(20, 80, 701, 144))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.slug_Scheme = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.slug_Scheme.setObjectName("slug_Scheme")
        self.verticalLayout.addWidget(self.slug_Scheme)
        self.Path_parts = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.Path_parts.setObjectName("Path_parts")
        self.verticalLayout.addWidget(self.Path_parts)
        self.Parsed_Query = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.Parsed_Query.setObjectName("Parsed_Query")
        self.verticalLayout.addWidget(self.Parsed_Query)
        self.list_Query = QtWidgets.QListWidget(self.verticalLayoutWidget)
        self.list_Query.setObjectName("list_Query")
        self.verticalLayout.addWidget(self.list_Query)
        self.table_Query = QtWidgets.QTableWidget(self.tab)
        self.table_Query.setGeometry(QtCore.QRect(20, 240, 701, 61))
        self.table_Query.setObjectName("table_Query")
        self.table_Query.setColumnCount(0)
        self.table_Query.setRowCount(0)
        self.button1 = QtWidgets.QPushButton(self.tab)
        self.button1.setGeometry(QtCore.QRect(20, 310, 75, 23))
        self.button1.setObjectName("button1")
        self.urlLineEdit = QtWidgets.QLineEdit(self.tab)
        self.urlLineEdit.setGeometry(QtCore.QRect(50, 20, 651, 21))
        self.urlLineEdit.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.urlLineEdit.setStyleSheet("font: 75 9pt \"Bitstream Charter\";\n"
"text-align: left;\n"
"css\n"
"QLineEdit#urlLineEdit {\n"
"  padding: 2px;\n"
"  border: 1px solid #ccc;\n"
"  border-radius: 4px;\n"
"  background-color: rgb(255, 49, 97);\n"
"  color: #000;\n"
"  font: 75 9pt \"Bitstream Charter\";\n"
"  text-align: left;\n"
"}\n"
"")
        self.urlLineEdit.setMaxLength(255)
        self.urlLineEdit.setCursorPosition(2)
        self.urlLineEdit.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.urlLineEdit.setObjectName("urlLineEdit")
        self.URL = QtWidgets.QLabel(self.tab)
        self.URL.setGeometry(QtCore.QRect(10, 20, 31, 20))
        self.URL.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.URL.setObjectName("URL")
        self.tabWidget.addTab(self.tab, "")
        self.tab_2 = QtWidgets.QWidget()
        self.tab_2.setObjectName("tab_2")
        self.label2 = QtWidgets.QLabel(self.tab_2)
        self.label2.setGeometry(QtCore.QRect(30, 10, 141, 16))
        self.label2.setObjectName("label2")
        self.lineEdit1 = QtWidgets.QLineEdit(self.tab_2)
        self.lineEdit1.setGeometry(QtCore.QRect(60, 30, 611, 20))
        self.lineEdit1.setObjectName("lineEdit1")
        self.tabWidget.addTab(self.tab_2, "")
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.Get_Task.setText(_translate("MainWindow", "Get_Task"))
        self.slug_Scheme.setText(_translate("MainWindow", "slug_Scheme"))
        self.Path_parts.setText(_translate("MainWindow", "Path_parts"))
        self.Parsed_Query.setText(_translate("MainWindow", "Parsed_Query"))
        self.button1.setText(_translate("MainWindow", "Button 1"))
        self.urlLineEdit.setText(_translate("MainWindow", "https://www.avito.ru/rostovskaya_oblast_aksay/tovary_dlya_kompyutera/komplektuyuschie-ASgBAgICAUTGB~pm?f=ASgBAgECAUTGB~pmAUXGmgwXeyJmcm9tIjoxMDAwLCJ0byI6NjAwMH0&q=E-MU+1616&s=1"))
        self.URL.setText(_translate("MainWindow", "URL"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), _translate("MainWindow", "Tab 1"))
        self.label2.setText(_translate("MainWindow", "Tab 2 Label"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_2), _translate("MainWindow", "Tab 2"))
