# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '/opt/opt2/PycharmProjects/main_avito_django_bot/avito_parser_django/avito/PyQT5/main_View_task_GPT_WINWER.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


